<a href="https://colab.research.google.com/github/Aaditya69Kumar/Company-Employee-Dataset-Cleaning/blob/main/Cleaned_Company_Employee_Dataset_Day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Cleaned Company Employee Dataset Using Pandas-IDRA


**Objective:** Clean a messy company employee dataset using Pandas. The analysis identifies missing values, inconsistent categorical entries, incorrect data types, and duplicate records. Appropriate cleaning techniques are applied, the dataset is verified after cleaning, compared before and after, and exported as a cleaned CSV file.

---
## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

## 2. Upload and Load the Messy Dataset

In [2]:
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print('Loaded File:', file_name)
display(df.head())

Saving Messy_Company_Employee_Dataset.csv to Messy_Company_Employee_Dataset (1).csv
Loaded File: Messy_Company_Employee_Dataset (1).csv

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

---
# 3. Initial Dataset Inspection

In [3]:
print('Dataset Shape:', df.shape)
print('Number of Rows:', df.shape[0])
print('Number of Columns:', df.shape[1])
print('\nColumn Names:')
print(df.columns.tolist())

display(df.head())
display(df.tail())

Dataset Shape: (157, 12)
Number of Rows: 157
Number of Columns: 12

Column Names:
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.6,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,MALE,43331.0,1.1,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.2,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.4,2020-11-19,NaN,2.0,Office
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [4]:
# Inspect data types and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [5]:
# Descriptive statistics
display(df.describe())
display(df.describe(include='object'))

              Age  Annual_Salary  Experience_Years  Performance_Score
count  153.000000     152.000000        154.000000         154.000000
mean    38.130719   89240.592105          8.990909           3.525974
std      9.361661   22626.172309          4.983874           0.930233
min     21.000000   43331.000000          0.600000           2.000000
25%     30.000000   71198.500000          4.450000           3.000000
50%     39.000000   90046.500000          9.350000           4.000000
75%     46.000000  107328.000000         13.200000           4.000000
max     52.000000  162942.000000         17.400000           5.000000

,Employee_ID,Employee_Name,Department,Job_Title,Gender,Joining_Date,City,Work_Mode
count,157,157,152,157,152,157,152,155
unique,150,130,10,23,5,147,13,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,Male,2025-08-17,Chandigarh,Remote
freq,2,3,23,13,75,2,24,56

---
# 4. Before-Cleaning Summary

In [6]:
before_summary = {
    'Rows': df.shape[0],
    'Columns': df.shape[1],
    'Total Missing Values': int(df.isnull().sum().sum()),
    'Duplicate Rows': int(df.duplicated().sum())
}

before_summary_df = pd.DataFrame([before_summary])
display(before_summary_df)

   Rows  Columns  Total Missing Values  Duplicate Rows
0   157       12                    32               7

---
# 5. Identify and Quantify Missing Values

In [7]:
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Values': missing_values,
    'Missing Percentage (%)': missing_percentage
})

display(missing_summary)

                   Missing Values  Missing Percentage (%)
Employee_ID                     0                    0.00
Employee_Name                   0                    0.00
Department                      5                    3.18
Job_Title                       0                    0.00
Age                             4                    2.55
Gender                          5                    3.18
Annual_Salary                   5                    3.18
Experience_Years                3                    1.91
Joining_Date                    0                    0.00
City                            5                    3.18
Performance_Score               3                    1.91
Work_Mode                       2                    1.27

### Missing Value Analysis
We inspect each column before choosing a cleaning method. Numerical columns will use **median imputation** because the median is less affected by extreme values. Categorical columns will use **mode imputation** because the most frequent category is a reasonable replacement.

---
# 6. Identify Duplicate Records

In [8]:
duplicate_count = df.duplicated().sum()
print('Number of Duplicate Rows:', duplicate_count)

if duplicate_count > 0:
    print('\nSample Duplicate Records:')
    display(df[df.duplicated(keep=False)].head(20))

Number of Duplicate Rows: 7

Sample Duplicate Records:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

---
# 7. Identify Inconsistent Entries
Categorical columns are checked using `unique()` and `value_counts()` to detect inconsistent capitalization and unwanted spaces.

In [9]:
categorical_columns = ['Department', 'Gender', 'City', 'Work_Mode']

for column in categorical_columns:
    print(f'\n{column}:')
    print('Unique Values:', df[column].dropna().unique())
    display(df[column].value_counts(dropna=False))

Department:
Unique Values: ['Marketing' 'Human Resources' 'Engineering' 'Sales' 'Finance'
 'Data & Analytics' 'Customer Success' 'Operations' 'ENGINEERING'
 'engineering']

Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

Gender:
Unique Values: ['Other' 'Female' 'Male' 'female' 'MALE']

Gender
Male      75
Female    68
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

City:
Unique Values: ['Pune' 'Mumbai' 'Bengaluru' 'Jaipur' 'Hyderabad' 'Chennai' 'Chandigarh'
 'Srinagar' 'Kolkata' 'delhi' 'Delhi' 'DELHI' 'Delhi ']

City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         11
Chennai       10
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

Work_Mode:
Unique Values: ['Office' 'Remote' 'Hybrid' 'REMOTE' 'remote']

Work_Mode
Remote    56
Hybrid    50
Office    47
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

### Problems Identified
The inspection reveals examples such as:
- `Engineering`, `ENGINEERING`, and `engineering`
- `Female`, `female`, and `MALE`
- `Delhi`, `DELHI`, `delhi`, and `Delhi `
- `Remote`, `REMOTE`, and `remote`

These entries represent the same categories but are stored inconsistently.

---
# 8. Create a Copy for Cleaning

In [10]:
# Keep the original dataset unchanged for comparison
clean_df = df.copy()

# 9. Clean Inconsistent Categorical Values

In [11]:
# Remove leading and trailing spaces
for column in ['Department', 'Gender', 'City', 'Work_Mode']:
    clean_df[column] = clean_df[column].astype('string').str.strip()

# Standardize capitalization
clean_df['Department'] = clean_df['Department'].str.title()
clean_df['Gender'] = clean_df['Gender'].str.title()
clean_df['City'] = clean_df['City'].str.title()
clean_df['Work_Mode'] = clean_df['Work_Mode'].str.title()

for column in ['Department', 'Gender', 'City', 'Work_Mode']:
    print(f'\nCleaned {column} values:')
    print(clean_df[column].dropna().unique())

Cleaned Department values:
<StringArray>
[       'Marketing',  'Human Resources',      'Engineering',
            'Sales',          'Finance', 'Data & Analytics',
 'Customer Success',       'Operations']
Length: 8, dtype: string

Cleaned Gender values:
<StringArray>
['Other', 'Female', 'Male']
Length: 3, dtype: string

Cleaned City values:
<StringArray>
[      'Pune',     'Mumbai',  'Bengaluru',     'Jaipur',  'Hyderabad',
    'Chennai', 'Chandigarh',   'Srinagar',    'Kolkata',      'Delhi']
Length: 10, dtype: string

Cleaned Work_Mode values:
<StringArray>
['Office', 'Remote', 'Hybrid']
Length: 3, dtype: string

---
# 10. Handle Missing Numerical Values Using Median Imputation

In [12]:
numerical_columns = ['Age', 'Annual_Salary', 'Experience_Years', 'Performance_Score']

for column in numerical_columns:
    median_value = clean_df[column].median()
    print(f'{column} - Median used for imputation: {median_value}')
    clean_df[column] = clean_df[column].fillna(median_value)

Age - Median used for imputation: 39.0
Annual_Salary - Median used for imputation: 90046.5
Experience_Years - Median used for imputation: 9.350000000000001
Performance_Score - Median used for imputation: 4.0

# 11. Handle Missing Categorical Values Using Mode Imputation

In [13]:
categorical_columns = ['Department', 'Gender', 'City', 'Work_Mode']

for column in categorical_columns:
    mode_value = clean_df[column].mode()[0]
    print(f'{column} - Mode used for imputation: {mode_value}')
    clean_df[column] = clean_df[column].fillna(mode_value)

Department - Mode used for imputation: Engineering
Gender - Mode used for imputation: Male
City - Mode used for imputation: Chandigarh
Work_Mode - Mode used for imputation: Remote

### Note on Other Missing-Value Methods
Pandas also provides `dropna()` and forward filling (`ffill()`):
- `dropna()` is useful when rows with missing values are unsuitable for analysis or contain too much missing information.
- `ffill()` is useful when observations have a meaningful sequential order, such as time-series data.

For this employee dataset, median and mode imputation are more appropriate because dropping rows would unnecessarily reduce the dataset, and forward filling could incorrectly copy one employee's information into another employee's record.

---
# 12. Correct Data Types

In [14]:
# Convert Joining_Date from object/string to datetime
clean_df['Joining_Date'] = pd.to_datetime(clean_df['Joining_Date'], errors='coerce')

print(clean_df.dtypes)

Employee_ID                  object
Employee_Name                object
Department           string[python]
Job_Title                    object
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                 string[python]
Performance_Score           float64
Work_Mode            string[python]
dtype: object

# 13. Remove Duplicate Records

In [15]:
rows_before_duplicates = len(clean_df)
clean_df = clean_df.drop_duplicates().copy()
rows_after_duplicates = len(clean_df)

print('Rows before removing duplicates:', rows_before_duplicates)
print('Rows after removing duplicates:', rows_after_duplicates)
print('Duplicates removed:', rows_before_duplicates - rows_after_duplicates)

Rows before removing duplicates: 157
Rows after removing duplicates: 150
Duplicates removed: 7

---
# 14. Verify the Cleaned Dataset

In [16]:
print('Missing Values After Cleaning:')
display(clean_df.isnull().sum())

print('Duplicate Rows After Cleaning:', clean_df.duplicated().sum())

print('\nCleaned Dataset Information:')
clean_df.info()

Missing Values After Cleaning:

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Duplicate Rows After Cleaning: 0

Cleaned Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    string
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    string
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    string
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    string
dtypes: datetime64[ns](1), float64(4), object(3), string(4)
memory usage: 15.2+ KB

# 15. Compare Dataset Before and After Cleaning

In [17]:
after_summary = {
    'Rows': clean_df.shape[0],
    'Columns': clean_df.shape[1],
    'Total Missing Values': int(clean_df.isnull().sum().sum()),
    'Duplicate Rows': int(clean_df.duplicated().sum())
}

comparison = pd.DataFrame({
    'Before Cleaning': before_summary,
    'After Cleaning': after_summary
})

display(comparison)

                      Before Cleaning  After Cleaning
Rows                              157             150
Columns                            12              12
Total Missing Values               32               0
Duplicate Rows                      7               0

---
# 16. Preview the Final Cleaned Dataset

In [18]:
display(clean_df.head(10))

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.40,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.80,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.00,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.10,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.50,2020-06-28,Chennai,4.0,Remote

# 17. Export the Cleaned Dataset as CSV

In [19]:
output_file = 'Cleaned_Company_Employee_Dataset.csv'
clean_df.to_csv(output_file, index=False)

print(f'Cleaned dataset successfully saved as: {output_file}')

# Download the CSV file
files.download(output_file)

Cleaned dataset successfully saved as: Cleaned_Company_Employee_Dataset.csv

---
# 18. Summary of Cleaning Steps Performed
1. Loaded the messy company employee dataset using Pandas.
2. Inspected the dataset structure, data types, and descriptive statistics.
3. Used `isnull()` to identify and quantify missing values.
4. Checked categorical columns using `unique()` and `value_counts()` to identify inconsistent entries.
5. Removed leading/trailing spaces and standardized capitalization in Department, Gender, City, and Work Mode.
6. Used **median imputation** with `fillna()` for missing numerical values: Age, Annual Salary, Experience Years, and Performance Score.
7. Used **mode imputation** with `fillna()` for missing categorical values: Department, Gender, City, and Work Mode.
8. Converted `Joining_Date` to the correct `datetime` data type.
9. Used `drop_duplicates()` to remove duplicate employee records.
10. Verified that the final dataset contains no missing values and no duplicate rows.
11. Compared the dataset condition before and after cleaning.
12. Exported the final cleaned dataset as `Cleaned_Company_Employee_Dataset.csv`.

# 19. Final Conclusion
The original dataset contained missing values, inconsistent categorical formatting, an incorrect date data type, and duplicate records. These issues were systematically identified and resolved using Pandas data-cleaning techniques.

Median imputation was selected for numerical columns, while mode imputation was selected for categorical columns. Text normalization removed inconsistencies caused by capitalization and extra spaces. Duplicate records were removed using `drop_duplicates()`, and the date column was converted to a proper datetime format.

After verification, the final dataset is clean, consistent, free from duplicate rows, and ready for further employee analytics or machine learning tasks.